server:
  port: 8080

spring:
  application:
    name: d-money
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888
#    consul:
#      host: localhost
#      port: 9994
  profiles:
    active: dev
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: el.grilgo@gmail.com
    password: unefmqhkiuiugzso
    protocol: smtp
    properties:
      mail:
        tls:
          enable: true
        smtp:
          auth: true
          starttls.enable: true
          tls.trust: smtp.gmail.com