server:
  port: 8080

spring:
  application:
    name: d-money
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888
#    consul:
#      host: localhost
#      port: 9994
  profiles:
    active: dev